# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guess.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 670)
        MainWindow.setMinimumSize(QtCore.QSize(420, 670))
        MainWindow.setMaximumSize(QtCore.QSize(440, 670))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ocr.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(5, 151, 242);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(60, 10, 321, 101))
        self.l1.setStyleSheet("\n"
"font: 75 60pt \"Candara\";\n"
"color: rgb(70, 2, 115);\n"
"\n"
"\n"
"\n"
"\n"
"border-radius: 40;")
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(60, 140, 321, 61))
        self.l2.setStyleSheet("font: 22pt \"Matura MT Script Capitals\";\n"
"")
        self.l2.setObjectName("l2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 570, 271, 81))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    \n"
"font: 36pt \"Matura MT Script Capitals\";\n"
"background-color: rgb(70, 2, 115);\n"
"border-radius: 30;\n"
"color: rgb(85, 255, 255);\n"
"}\n"
"QPushButton:pressed { \n"
"    \n"
"    \n"
"    background-color: rgb(85, 0, 255);\n"
"    \n"
"    \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(90, 240, 275, 71))
        self.radioButton.setStyleSheet("QRadioButton{\n"
"font: 29pt \"Candara\";\n"
"background-color: rgb(70, 2, 115);\n"
"\n"
"color: rgb(85, 255, 255);\n"
"}\n"
"QRadioButton:pressed{\n"
"    background-color: rgb(170, 85, 255);\n"
"}\n"
"QRadioButton::indicator { width:30px; height: 27px;}")
        self.radioButton.setObjectName("radioButton")
        self.btn_easy_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.btn_easy_2.setGeometry(QtCore.QRect(90, 340, 275, 71))
        self.btn_easy_2.setStyleSheet("QRadioButton{\n"
"font: 29pt \"Candara\";\n"
"background-color: rgb(70, 2, 115);\n"
"\n"
"color: rgb(85, 255, 255);\n"
"}\n"
"QRadioButton:pressed{\n"
"    background-color: rgb(170, 85, 255);\n"
"}\n"
"QRadioButton::indicator { width:30px; height: 27px;}")
        self.btn_easy_2.setObjectName("btn_easy_2")
        self.btn_easy_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.btn_easy_3.setGeometry(QtCore.QRect(90, 440, 275, 71))
        self.btn_easy_3.setStyleSheet("QRadioButton{\n"
"font: 29pt \"Candara\";\n"
"background-color: rgb(70, 2, 115);\n"
"\n"
"color: rgb(85, 255, 255);\n"
"}\n"
"QRadioButton:pressed{\n"
"    background-color: rgb(170, 85, 255);\n"
"}\n"
"QRadioButton::indicator { width:30px; height: 27px;}")
        self.btn_easy_3.setObjectName("btn_easy_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Угадайка"))
        self.l1.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:48pt;\">Угадайка</span></p></body></html>"))
        self.l2.setText(_translate("MainWindow", "Выберите уровень:"))
        self.pushButton.setText(_translate("MainWindow", "Играть!"))
        self.radioButton.setText(_translate("MainWindow", "    Лёгкий"))
        self.btn_easy_2.setText(_translate("MainWindow", "   Средний"))
        self.btn_easy_3.setText(_translate("MainWindow", "  Сложный"))
